#!/bin/bash

# Run AAD on the dataset
# TODO: OML ALWAYS FLAGS SHOULD BE ADDED TO THESE COMMANDS
#############
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed

# Different Conservative Threshold
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_nok

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i --identity

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok --identity

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok --identity

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_i_nok_wup --identity --w_upper 5.0

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --save_suffix normed_i_nok_wup --identity --w_upper 5.0

############################
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_wup --identity --w_upper 5.0

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --oml_always --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_i_wup --identity --w_upper 5.0

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_i_noml --identity

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --use_top_k --save_suffix normed_10_noml 

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 40 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_thresh --save_suffix normed_10_nok_noml

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_anom --prime_anomalies --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal --prime_nominals --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_anom_10 --prime_anomalies --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 10 --true_feedback --use_oml --use_top_k --save_suffix normed_nominal_10 --prime_nominals --oml_always


# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok --prime_anomalies --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok --prime_nominals --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_anom_nok_noml --prime_anomalies 

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data abalone --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mammography --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data thyroid --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data weather --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cancer --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nominal_nok_noml --prime_nominals 


# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml 

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok --oml_always
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok --oml_always

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_mahal --oml_always --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_mahal --oml_always --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_mahal --oml_always --use_mahal

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml_mahal --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml_mahal --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml_mahal --use_mahal 

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_mahal --oml_always --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_mahal --oml_always --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_mahal --oml_always --use_mahal

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml_mahal --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml_mahal --use_mahal
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --conserv_thresh 50 --true_feedback --use_oml --save_suffix normed_nok_noml_mahal --use_mahal







# ##########
# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20
# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20
# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight  --conserv_thresh 50  --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight  --conserv_thresh 50 --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20
# ###############

# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20
# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20
# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20
# # python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_anom_only_deweight  --prime_anomalies --prime_limit 20
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight  --conserv_thresh 50 --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight  --conserv_thresh 50 --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight  --conserv_thresh 50 --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight  --conserv_thresh 50 --true_feedback --save_suffix normed_nok_nom_only_deweight  --prime_nominals --prime_limit 20







# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_nok_deweight

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data imagenet --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --save_suffix normed_nok_full_deweight

#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data imagenet --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo
#python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --opo --save_suffix normed_nok_full_deweight_opo


# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_99_deweight --use_thresh --selection_thresh 99

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --save_suffix normed_fullk_95_deweight --use_thresh --selection_thresh 95
 
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 5 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k5_deweight

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 10 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k10_deweight

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 15 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k15_deweight

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 20 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --use_top_k --save_suffix normed_nok_k20_deweight

# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data imagenet --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data oxford --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data unsw --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data campaign --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data bank --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data nslkdd --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data msl --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar_airplane --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cifar_bird --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion_boot --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data fashion_sandal --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data mnist --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data svhn --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cover --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data higgs --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data spam --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data census --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data cardio --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight
# python src/aad_metric.py --data_path /mnt/c/Users/xdink/Documents/Research/OnlineMetricLearning/data --data yeast --iters 50 --k 3 --v 1e-7 --original_mu --nom_deweight --conserv_thresh 50 --true_feedback --full_k --v2 --save_suffix v2_nominal_deweight